### ISSUE TITLE
Move samples to this repository

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-talent#57]
I was looking around at samples, and noticed these over here:
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/talent-v4beta1-samples/jobs/v4

We really should have these in the `samples/` dir in this repo, so it's consistent with the rest of the node.js repositories.

**Comment by beccasaurus** [comment]
Those samples are not to be merged, they're pending a design implementation.

Talent v4beta1 samples will hit all 7 language client library repos in the coming weeks :)

**Comment by czahedi** [comment]
Justin that link seems dead. I assume this has been resolved unless I simply don't have access?

**Comment by JustinBeckwith** [comment]
Even better.  At some point, someone deleted the branch.  Now, this tab for nodejs is empty:
https://cloud.google.com/talent-solution/job-search/docs/libraries#client-libraries-usage-nodejs

There are however out of date samples here, that use the apiary based libs :|
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/jobs

**Comment by fhinkel** [comment]
> Even better. At some point, someone deleted the branch. Now, this tab for nodejs is empty:
https://cloud.google.com/talent-solution/job-search/docs/libraries#client-libraries-usage-nodejs

The branch `talent-v4beta1-samples/` was merged into master and then deleted,  see https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/1801. 

The Node.js tab in the docs uses sources from this repo. That got fixed in October.

I opened an issue in `nodejs-docs-samples` to delete the samples after making sure we don't use them in the docs anymore. See https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/2103
